name: deepfake_mobile
description: VeriFake - AI-powered deepfake detection app
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.2.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  dio: ^5.4.0
  flutter_dropzone: ^4.0.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  animate_do: ^3.1.2
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
